skillMetadata:
  sections:
    - name: Webhook
      fields:
        - type: label
          label: Enter the webhook url to call when a command is processed
        - name: webhook_url
          type: text
          label: Webhook URL
          value: ""
        - type: label
          label: HTTP Method
        - name: http_method
          type: select
          label: Method
          options: POST|post;GET|get
          value: post